package com.goSmarter.drools.banking   //是必添项，但名称不做要求，为统一方便管理，与其位置路径一致。
import com.prowo.drools.Person      //是必添项 ，引用的实体类

rule "boy"
    salience 1
    when
        $p : Person(age > 0);
    then
        $p.setDesc("少年");
        retract($p);
end

rule "youth"
    salience 2
    when
        $p : Person(age > 12);
    then
        $p.setDesc("青年");
        retract($p);
end

rule "midlife"
    salience 3
    when
        $p : Person(age > 24);
    then
        $p.setDesc("中年");
        retract($p);
end

rule "old"
    salience 4
    when
        $p : Person(age > 60);
    then
        $p.setDesc("老年");
        retract($p);
end
